# Generated by Django 3.1 on 2020-08-17 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('message_publisher', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='pub_date',
            field=models.DateTimeField(auto_now_add=True, default='2020-08-17 17:55', verbose_name='Дата публикации'),
            preserve_default=False,
        ),
    ]
